#!/bin/bash
set -e
./gradlew publishAllPublicationsToCentralS01Repository
# Publish on GitHub. Fails due to overwritings, so it's ok to give up
./gradlew publishAllPublicationsToGithubRepository --continue || true
