_reference-jdk: &reference-jdk
  'JDK="adopt@1.8"'

language: bash

git:
  depth: false
  autocrlf: input

os:
  - osx
  - windows
  - linux

addons:
  apt:
    packages:
    - graphviz

stages:
  - check
  - test
  - name: deploy
    if: type != pull_request AND repo = DanySK/jirf

env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - *reference-jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@"
    - JDK="adopt-openj9@"

jobs:
  exclude:
    - os: linux
      env: *reference-jdk
      stage: test
  include:
    - stage: check
      name: "Compile, check, test on reference JDK"
      os: linux
      env:
        - *reference-jdk
    - stage: deploy
      name: "Preparation of reports and deployment"
      os: linux
      env:
        - *reference-jdk
        # Signing
        - secure: "lheD5/Ilby/lnPP5moykYRsspSn0f21bl6exkNM0Td07CD6OW2DhCWtyiDoA8vazuMSZCmHfIroedwK7zxwzgO1fl1HeOgG08S2+hyab6+GErrUICZVifxHuJiyeSRmN3s0t2ZJfTqK7lc5Dsh9EYdWB5hp/HkTMIYyJcRo53JYREQV3H3mbbeecoermustlCO2eH1PdtOxuVgPtnwxccVZDRJt6x25PQyZ5FR9QQivZeQ0AYwN96zodIeth9Y9kZk0RkZUvj1Q6pPQwcYX1ukZ7dBr09J9D/nSsN62qYK+lBZeaF51Nuv5d/L8VtKssu9GsGO+8NAQTwgCRwGOVhhGJ8aTiYStsfK5QeaHVgGkBQ1eQ5cwhMhSjXQm0z/8k/R/mFfDtMTkSIAtYRjNj7l0oYxvkj5UILfxoEnZeK6HIXHy7viZwUXgfRPrFK2WgI7Ko3lDZOAJ8X1HDQDMxM6rRuEqV/evJRF6RlhqnAluG2+Op/tcWbTLp4nW6sase+j3+ZOmi9/Yyzm3wNwqdl0PMhpr9Q3b7MW4cpfT8lbDDdm5hOQ/Q8FFPTnRSxGzrM+jAHNG9uxn5MKg1MNew/NxYDa/pg5sZ1IcAPvZizs5db8Z5pSnX539enPkugODhtU5z09CojcEv2+m6Ei88dKh/PEkIxvcI5M0aH9qZ1g4="
        # Central
        - secure: "P+OdKGQ2sRl4oN6OTfCyqfdz1jAEFij8ymwnxjhm02k2Qh4tp3/L1tmPgrlZwRz4z4WIALs+yUs5fGYU6YSVV8FRhui6WMT8mlEjcaEHt4ZXazqe5mZ7GGlBjRsXFzVzTUP/8ruIiYmoR0xC/bCKXMR3yjlgPEYB8ygwjayB3Dwzluf8fUjBrAaEZ6NrC2U8KlkE1PhoujJGKTTVEhnFGjCJ732KbwUMDLsy6Uzz4+ajRnBNiz6/l6fgnGlL3UwoZd3TX5jgBEs2cWYcxHFX8D03zVbcC0AkOw4yIS66owFzgq0L5NiBRZixkeuCG79Fdp0l8YXEbETYSahrjnCsZL+NFyPzGK4zx0RwJMOXfZ1G0OvzXQIPtZ6bfFssbcBRu82GtSYO1sSjOtrvuI0Ak9m39FAobF+UaowIppasNDTIl0Mk0sKrMnKN5fuGlGvotWImZHMIS3h1+tSNrVqUz8V4JpVqGprnjj+v3Hb//jMf3MZxZr9tlZEk6G0aDY8PjaozIhyar75U3Ryap+/RmSCquhAMTucNfKE98JbmPglcMvy8WhhWW0TKU2mCDNBYpVHLy5/lp1vFn25IRSRQ0rX5EbYR1A+UaHKNfUUZVo3kLIPjz3/ikNk25b1Ot1ATDgB50CTSsflIQsvaMwLPHLJoWNfSU7hLfELy2uP12OM="
        - secure: "dwp0bVrNWwcWorPMWZHw+3EAzFKWYSHhsA+WgQ7vIRw4KoPI7ydZKesnd6vBxAwXOHh1RG9iYgkmUHeQotH8PtPqDTvr5ONJWo5aIty7bw6z3AJjJyHY8zzrbwWbi1dKWyJLdVSf7dgpd5JY1PtuOvx9o5qiKcIDHeQLeqCDThzX5a0nCE4AuTCCdGKtEXaZVGTpszxAy3rcPv0+ebsmJbnElxy2xkd8g7qDTmTImxMNqyUwCeJYpLBH5ZOoirg7H2/BhfwBggYy8XvdLFmge2J06s7wIjZIso+HldvK4kFbOSIiIXy+SoCWXP1Le+HUueznmOZTfwpcRYpkx/dbJh1FJLT+t10ayKt+yHTr/hn0GJkKBNzbIX5hJulSuxDYWfcuX90sBd+TlIevuFXvyb/eCeaRHc9RPA4MTXi2Fxe3936zl0gGFTkwFHD7Tcv/r/w+TXxze0kaHQzHjZWc5+O3TSFZr/8nbuU5feScdUeogP5jQy4UI/CWnZCYfQFz2Rj9cmP/ynlEKBz5crBVKC1VFQAO3Iv4soZkZLbCuDTzumtEOfxIzIvPuNsIMAyXH6IZg/PqV4xfzigIEXLc89W5o4J1JWx0USAIi0owsJowkYYAM4o+4++ZDUCuSHSL3xCaOGg2JoeRCnsFdTAAykaI1VD4eypFdjv37JZzBwo="
      install:
        - openssl aes-256-cbc -K $encrypted_ae2fe9b21dcc_key -iv $encrypted_ae2fe9b21dcc_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - travis_retry ./gradlew publishAllPublicationsToMavenRepository

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

script:
  - travis_retry ./gradlew check

before_cache:
  - $GRAVIS/clean-gradle-cache

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
