language: bash
os:
#  - linux
#  - osx
  - windows
env:
  global:
    - secure: "B+bmocGqYSk0KOE5dNKtIGpHJw/U1idHWpSxT/xPGZ2EZBBe8l1KBDRkj160xXE2nmjyFHwgPLGrpAzRoHQ7hf7E0jzPJgMy4YHIaxjQarO3EFcIQgpZFirRngt/yJVqzfEVt9uL+GhThTwprId14eDrTg1eAz862QXCBh7ZlK23d+khjR2exEfq66EJi4nLfvJuI8krK/4UP97qs9N3NupcXfuRETk6yNvdSazGSKkeykipoIbSUaLIRpa0hoy/e4jmBvNxqO9gY1LSu1wc7b51G478CeGyTrtcUP9p3DhJPCL1Gp7FWr+13GtLTiGrSjqkhJaRU2CD11ulzBqd8FrtAqhxggzc7A4WKFtBi8FA1TObAkyz+416riiFfff+NLPFtB9Fx4Ky6vuthF/LLb+w/3X9kflraqX75KYw27UZbpJLzXzfZeI8eQRpdLOlLU+3qqHwwdnpf6fKX8wDlp4flL+sGz5692VEeCSA8BBuUNeWSFuOAmNhol1boCCnF2lpWBcjyMUJFgzMbpZQXLasbgmKsL35QV2N8JxRC1U1pocQfx+r/b09AyJasvnY9tFUr5CgoHafVLWR2AqxS+p3CEVWNa3yqG2ntSU9rhWUsQBk9qV+j7sWaAoqUsamAogAIujvIRY2+kkoxQLyQPOcog66ATDARH/24OFUDXU="
    - secure: "oIo/BpZrS9syZD95ugLjhKd6LRHHVyyPz85NA0Ka8G4sQi3LUYVk6/pizlt9a3QGjr5b8+XUHrh1TdmgyO56BGryKsz2k/L6LhTSsCPgWIvryV3Y8fEVkeh7mVHnAzxlJX6gbMxyubDOpUep3fWZmzmv/WmhCNn8SBNAEwXaVGoeTu+xepWYUakJ2c+nhXf7fI0lejXlndNfGNXVvtvb830Dx2tIWLDOJmTNB8sGRGytKpH/z+p/7PrVXEh3VarSlTRVAAOkAzFyWyMJD/YNxcKYRO958BlVYXep6ibmmaEyPRbqEnl7tTAF4oRUPwu1c2Ej3OlBGFEWmxuYR9p1AG0zz7R8IIbQm3kq9QtrUCe1PgayQxlArc+ERIXHFuXpRyBo8Y5PSNXcwqRW50WVRAchUt8P+btHhc2JFn0GdyEma+3OlkicAR3iHeQENJib9dJwhj3skCI1FGe74D9Og3DsSzqF8bgjbC1erMILZJ8d1+RSy0217e+EJYi9CO9EADgXMDbZRtgDUmLvstvcGxpkYJRmY04QrYpRbDzxuGFmoZ7/87RiJAfoCLwOGyiMow0tmw0ek4h9o8Iv+ekjS8WxEPotKkLEcAfWaXUgEEsWqXsDyFup91Dy236M106K2EZQTzbJLgMtL+g694jE+22DLxs57TZL327V8Tuj6+I="
    - secure: "icOCfQWB64+WMi6/Z/gMyjO53PDMyy0t3zLGQZbzoNofjHvyumwsCTlJVtuSe3KLv1FcmT68/D6QkcznlAx5VX8DB+KOGPMLc06C1oEd0skcLQ+nHzq14thac18MtxFgt67wVl2BN0lhazgByJpSzre6A7SmStBEaMXKfWB9uwvf58TCoDhx05PV4Jgj1VEyoO7jGNxzz1j5+C+IcfDrg0JEX0Ykzr1wXoGSKpQdANCmBuRO/EzfTudJie5x2/VDUyedM9dfT19lmN2XpEZEppZAXpyWg0tpd5WPSH8Ts5IgBfKtzQUL1djkBlr0e565QgfmWeiJD3YxeHRKem00jAOWC6IQrW/TDyke2bCicioHWIkMXnON71mkJXC/meMftryumJych8uXc97zdDw079r+3yXCla46ExO6WZiItrcIMTtM6ps06ZCeItEfpvnKkPQwEpj/zhkC4Kv8ULmtyL0dHBu6IuMQf0grRLwgBLi5yy7DQoeU29xmL+3fNiYa9R8ez00n5ENc53zO1guByHojpKuaICu46jj/zDmzoohmvd/Zpfpw4+MkfF5dOxl4mDaAAJ+qXCGozqg9c9YyewE6W2gwugd/OfsqjMu/WK71ZFL4/EH3QUHRQBaQdCm5mmWm65gcWCNHuHZyum3igUh0qJG5pTM9qiFls3P/1xA="
    - PUBLISH="false"
  matrix:
    - JDK="adopt@1.8.212-04"
matrix:
  include:
    - env: PUBLISH="true" JDK="adopt@1.8.212-04"
  exclude:
    - os: linux
      env: JDK="adopt@1.8.212-04"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - find $HOME/.gradle/caches/ -name "buildSrc.jar" -type f -delete
  - find $HOME/.gradle/caches/ -name "file-access.bin" -type f -delete
  - find $HOME/.gradle/caches/ -name "user-id.txt" -type f -delete
  - find $HOME/.gradle/caches/ -name "*.lock" -type f -delete
  - find $HOME/.gradle/caches/ -name "cache.properties" -type f -delete
  - rm -f $HOME/.gradle/caches/*/fileHashes/*.bin
  - rm -fr $HOME/.gradle/caches/*/workerMain/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.jabba/
before_install: |-
  bash .install-jdk-travis.sh
  if [ $TRAVIS_OS_NAME = 'linux' ]; then
    sudo apt-get -qq update;
    sudo apt-get install -y graphviz;
    export SHOULD_CONFIGURE="$(if [ $TRAVIS_PULL_REQUEST = "false" ] && [ $TRAVIS_REPO_SLUG = 'DanySK/jirf' ]; then echo 'true'; else echo 'false'; fi)"
  else
    export SHOULD_CONFIGURE="$(echo 'false')"
  fi
install: >-
  if $SHOULD_CONFIGURE; then
    openssl aes-256-cbc -K $encrypted_ae2fe9b21dcc_key -iv $encrypted_ae2fe9b21dcc_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
    bash prepare_environment.sh
  fi
script:
  - echo "SCRIPT BEGINS"
  - echo "Java home is set to: $JAVA_HOME"
  - echo "Path is set to: $PATH"
  - echo "Current content of .bash_profile:"
  - cat ~/.bash_profile
  - ./gradlew clean check --scan --parallel
after_success: >-
  if $SHOULD_CONFIGURE && $PUBLISH; then
    ./gradlew publish --parallel
    mkdir -p report
    cp --parent */build/reports build/reports report -R
  fi
