language: java
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_1918c4c7167d_key -iv $encrypted_1918c4c7167d_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
  - sh prepare_environment.sh 
script:
  - ./gradlew
  - ./gradlew uploadArchives
  - ./gradlew closeRepository || exit 0