import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * https://github.com/google/guava */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * http://junit.org */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * http://commons.apache.org/proper/commons-lang/ */
    const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

    /**
     * https://github.com/DanySK/boilerplate */
    const val boilerplate: String = "org.danilopianini:boilerplate:" + Versions.boilerplate

    /**
     * http://www.jgrapht.org */
    const val jgrapht_core: String = "org.jgrapht:jgrapht-core:" + Versions.jgrapht_core
}
